---
name: Release and Dispatch Homebrew

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dispatch:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.result == 'success' }}
    steps:
      - name: Get Version
        id: info
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"

          wget https://github.com/peter-bread/gamon/archive/"$VERSION".tar.gz
          CHECKSUM=$(sha256sum "$VERSION".tar.gz | cut -d ' ' -f 1)

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "checksum=$CHECKSUM" >> "$GITHUB_OUTPUT"

      - name: repository dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.HOMEBREW_PAT }}
          repository: peter-bread/homebrew-gamon
          event-type: release
          client-payload: |-
            {
              "version": "${{ steps.info.outputs.version }}",
              "checksum": "${{ steps.info.outputs.checksum }}"
            }
