on:
  release:
    types: [published]

jobs:
  update_formula:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Update Homebrew formula
      run: |
        SOFTWARE_USERNAME=peter-bread
        SOFTWARE_REPO=gamon
        TAP_USERNAME=peter-bread
        TAP_REPO=homebrew-gamon
        FORMULA_NAME=gamon

        # Get the new version number from the tag
        VERSION=${GITHUB_REF#refs/tags/}

        # Download the tarball to calculate the SHA-256 checksum
        wget https://github.com/$SOFTWARE_USERNAME/$SOFTWARE_REPO/archive/$VERSION.tar.gz
        SHA256=$(sha256sum $VERSION.tar.gz | cut -d ' ' -f 1)

        # Clone the tap repository and check out a new branch
        git clone https://github.com/$TAP_USERNAME/$TAP_REPO.git
        cd $TAP_REPO
        git checkout -b update-$FORMULA_NAME-$VERSION

        # Update the formula file
        sed -i "s/^  url .*/  url \"https:\/\/github.com\/$SOFTWARE_USERNAME\/$SOFTWARE_REPO\/archive\/$VERSION.tar.gz\"/" Formula/$FORMULA_NAME.rb
        sed -i "s/^  sha256 .*/  sha256 \"$SHA256\"/" Formula/$FORMULA_NAME.rb

        # Commit and push the changes
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git commit -am "Update $FORMULA_NAME to $VERSION"
        git push origin update-$FORMULA_NAME-$VERSION

        # Create a pull request
        gh pr create --title "Update $FORMULA_NAME to $VERSION" --body "" --base master --head update-$FORMULA_NAME-$VERSION
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}